---
author: lam
title: "From Aristotle to Dennett: on Consciousness and Wakefulness"
date: 2020-01-25
reading_time: true
categories: ["neuroscience", "philosophy", "psychology"]
tags: ["consciousness", "cognition"]
slug: consciousness-wakefulness
description: >
  Consciousness, as a hard problem, first came as a philosophical enquiry.
  Current endeavours on neuroscience and psychology start to elucidate the
  essential building block on a conscious moment. Discussed in this review are
  four theories on such a concept.
summary: >
  Consciousness, as a hard problem, first came as a philosophical enquiry.
  Current endeavours on neuroscience and psychology start to elucidate the
  essential building block on a conscious moment. Discussed in this review are
  four theories on such a concept.
csl: ../harvard.csl
bibliography: ref.bib
draft: false
---

# Introduction

> ...every one who is awake perceives either some external movement or else some
> movement in his own consciousness...a soulless body has not the potentiality
> of perception.  
>  
> --- Aristotle, *on Sleep and Sleeplessness*

A question on consciousness, and consequently free will, is an enigmatic and
inexplicable query. Are we all beings controlled by homunculus and/or the imp
of perversion? Do we comply with the view of our thought, vis-à-vis, what
Descartes summarized as cogito ergo sum? Numerous studies and thought
experiments attempted to delineate such queries resulted in the propagation of
dismal rationalization, whereby said questions regarded as hard-to-solve
problems. This review, highly influenced by @Cleeremans2019, aims to
discuss proposed models in explaining consciousness published in the past five
years.

# First-order Representation

In first-order theory, consciousness divided into *access conscious* and
*phenomenal conscious*, where @Mehta2013 further elaborated their arguments on
how phenomenal consciousness could interpret current experimental findings by
the time of their publication.  Phenomenal consciousness refers to an event of
heightened awareness of certain environmental changes. Such changes may occur
alongside general and specific representation as percepts, where general
percepts explain what state ones currently in and how they differ from being
unconscious. Meanwhile, specific percepts represent differences in one stimulus
from others.

Said interpretation in specific percepts resemble dictionaries with key-value
pairs, where the associated key would grant access to a defined value. Akin to
the actual dictionary, one can associate a simple terminology (e.g.  "book")
with a definition (e.g. "a set of written sheets of skin or paper or tablets of
wood or ivory").  However, instead of utilizing a hard-coded key, @Mehta2013
suggested a context-derived key from its paired value. It implies a level of
abstraction during key registration in our conscious mind, i.e. when we
perceive a book we would not simply imagine a set of written sheets of paper;
rather we would represent the book as a concept of such a definition.
Hypothetically, neural correlates on the first-order consciousness arise from
sensory systems mediated by thalamocortical relay, suggesting the presence of
reciprocal loops during sensory processing, resulting in information
integration [@LenDomnguez2019].

# Higher-order Representation

Higher-order representation happened in a post-sensory system
[@LenDomnguez2019], which enable first-order representation monitoring. Such
monitoring results in inner awareness [@Brown2019], akin to a
meta-representation on lower-order ones. The necessity of having higher-order
representation lies in the inability of first-order representation to
completely engender consciousness. As such, higher-order representation is an
umbrella term defining awareness importance in generating a conscious
experience. The process underlying higher-order representation itself does not
equate with consciousness for it happens unconsciously. Consciousness emerges
as an outcome from such a process, denoted by a certainty in perceiving
preceding events. Inherently, metacognition poses a direct relationship with
said representation, where higher-order representation potentially elicits
metacognition.

# Global Workspace

Global workspace, as a part of working memory, emerges information into
globally available frameworks for further mental processing [@Baars2005;
@Shea2019].  Consciousness, alongside attention, would selectively allow
represented information to enter the global workspace in a goal-directed
fashion.  Interestingly, said working memory does not require sustained neural
activity in the prefrontal cortex (PFC), implying dynamic information
representation [@Stokes2015]. Dynamic working memory formation shall assume
short-term synaptic plasticity (STSP), where encoded information can undergo
abrupt disconnection without affecting the memory registry [@Stokes2015].
Considering consciousness as a necessary apparatus affecting the mental process,
such findings may suggest consciousness as having other roles rather than
merely maintaining working memory within the global workspace.

Reflection on a particular mental state is an important facet in having
conscious experiences [@Shea2019], where such a reflection may arise from
metacognition, i.e. the ability to recognize cognitive process outputs
[@Fleming2014]. Therefore, @Shea2019 hypothesized a certain degree of
metacognition parameters involvement in cognitive process-related mental tasks
served by the global workspace to ensure effective performance. In a
task-driven activity, a subject may require information to undergo three
processes of input, transition and output. During input, information emerges as
a conscious event through a global broadcast into the dedicated workspace. The
transition phase is the manipulation and comparison of such information,
whereby metacognition parameters becomes indispensable, especially confidence
judgment in determining certainty and uncertainty [@Kepecs2012; @Shea2019].
Finally, the output process will express processed information as an action or
verbal report. Conscious access to the global workspaces marked by elevated
activity in the frontoparietal and medial temporal cortex [@Baars2005]. The
presence of metacognition is necessary to invoke inner awareness on the ongoing
mental process, where such a presence may generate higher-order representation
from the general workspace.

# Quantum Theory and Consciousness

Based on observer's effect postulate in quantum mechanics, quantum realms
received attention in its potential to elaborate consciousness and merge the
body-mind duality. Quantum tunnelling effects on neurotransmitter exocytosis
[@Georgiev2018], psychons [@Eccles1992] as mental microunits transmitting
consciousness-related information [@Beck1992] and Orchestrated
Objective-Reduction (Orch-OR) [@Hameroff2014] are but a few of numerous
proposals in illuminating the hard question. Chemical connection on the
synaptic bouton happens due to neurotransmitter exocytosis, which releases rate
influenced by momentary probability increase following selections of events
(quantum tunnelling) process. Psychons, as microunits ubiquitously present in
the nervous system, would selectively propagate encoded consciousness-related
information from pyramidal cells to apical dendrites. Meanwhile, Orch-OR theory
proposed microtubules vibration, resulting in quantum interference
superposition and collapse. Initially, quantum vibration starts due to ionic
composition changes-related phosphorylation at a very short distance
approaching zero of $d: d \to 0$, where $d$ eventually widen during an
infinitesimal amount of time, resulting in superposition. Subsequently,
superposed mass-energy will accumulate and reaching a certain threshold of
quantum gravity. Considering microtubule as a nanocomputer with
self-stabilizing logic algorithms, such a superposition would stabilize and
collapse into one definitive state, where @Hameroff2014 proposed said state as
a discrete and independent conscious moment [@Li2019].

# Conclusion

Albeit myriad theories on consciousness, we are yet to achieve concrete
neurobiological correlate on this particular day-to-day experience.
Contributions from first-order and higher-order representation alongside global
workspace as well as quantum theory have widened our perspective in understanding
the nature of consciousness. However, could the hard question on consciousness
be chimeric? To conclude this review, I would present a
quote from @Dennett2018:

> The key to a unified account (of consciousness and free will) lies...in the
> recognition...that open-endedness of human brain's representational power
> is...both the problem and the solution...  
>  
> --- Daniel C. Dennett, *Facing up to the hard question of consciousness*

# References
