---
author: lam
title: Giftedness and The Curse of Expectation
slug: gifted-student
date: 2020-02-29
categories: ["psychology"]
tags: ["cognition", "intelligence"]
reading_time: true
bibliography: ref.bib
description: >
  We often regard intellectual prowess as a natural gift, bestowed upon
  individuals irrespective of their background. Gifted individuals may possess
  better academic performance compared to their agemates. However, no such a
  definition has adequately surmised a boundary on the percept of intelligence,
  left alone gifted. Several model attempted delineating giftedness, which we
  shall explore as a common foundation for further discussion.
summary: >
  We often regard intellectual prowess as a natural gift, bestowed upon
  individuals irrespective of their background. Gifted individuals may possess
  better academic performance compared to their agemates. However, no such a
  definition has adequately surmised a boundary on the percept of intelligence,
  left alone gifted. Several model attempted delineating giftedness, which we
  shall explore as a common foundation for further discussion.
csl: ../harvard.csl
draft: false
---

# Introduction

We often regard intellectual prowess as a natural gift, bestowed upon
individuals irrespective of their background. Gifted individuals may possess
better academic performance compared to their agemates. Surrounded by highly
expecting parents, peers and social environments, gifted individuals often
encounter emotional problem such as anxiety and perfectionism tendency
[@Guignard2012] as well as depressive traits [@Bnony2007]. However, no such a
definition has adequately surmised a boundary on the percept of intelligence,
left alone gifted. Several model attempted delineating giftedness, which we
shall explore as a common foundation for later sections.

# Giftedness Model

Numerous studies elaborated their perspective in modelling giftedness, where
@Worrell2019 summarised into three categories of ability-driven, talent
development and integrative model. In early days when IQ measurement developed,
investigations on IQ as the conceptualization of giftedness sprung, raising the
notion of gift as an innate potential ability. However, some findings partially
object such a notion, and suggested talent development in gifted children what
truly define gifted adults. Integrative model intermediated differing views on
previously described concepts, proposing focuses beyond academic achievements.

Firstly elaborated by Terman, gifted individuals regarded as those with
high IQ, indicating adept general intelligence, which later modified in
triarchic theory. Coined by Sternberg, three facets of general intelligence
consists of analytic, creative and practical intelligence, each serves to
acquire, process and actively deal with novel information. Furthermore, Gardner
proposed field-specific intelligences, termed as multiple intelligence. Such a
notion comprises of linguistic, logical-mathematical, musical,
bodily-kinesthetic, spatial, interpersonal and intrapersonal. On later
publication, Gardner appended additional components, including naturalist,
spiritualist and existentialist, into his model. Said proposal was akin to
Occam' razor in scrutinizing the presence of intelligence to create outcome of
value in a social and cultural settings.

Viewing intelligence as talent developments, Tannenbaum considered gifted
individuals as those with innate prowess well-culminated by external
environment, resulting in optimal development. Such a fulfillment in children
potential including general and specific ability, which later argued by Renzuli
in the three-ring conception model. Renzuli suggested three requirements to
develop talent: task commitment, creativity and above-average performance,
which aligned with enrichment, problem solving and productivity respectively.
To further differentiate internal and external factors, Piirto proposed
pyramidal model where the four-level pyramid represents the internal values and
the surrounding represents external ones. Base of pyramid, in alignment with
Gagne's view, has underlying biological property in defining intelligence. The
later levels will have personality, cognitive, talent and drive to determine
personal capability. Piirto regarded environmental values as chance factors,
to which an individu has no control upon. Further supported by Ziegler and
Bloom, which the former suggested dynamic interaction between personal and
environmental values while the latter emphasized on initial (mis-)conduct in
determining individual (in-)aptitude to a specific domain.

# Social Pressure and Potential Solutions

A few studies addressed possible problems arising with giftedness, including
higher perceived social pressure on individual achievement, leading to anxiety
and perfectionism [@Guignard2012; @Bnony2007]. Considering the role of pressure
as a regulatory focus [@Worthy2009], it may seem appealing to reason such a
pressure as an indicator on prevalent psychological issues in gifted
individuals.  However, the lack of evidences on said problems could lead into
non-sequitur arguments in defending social constructs as a potential bottleneck
in culminating individual talent and innate cognitive prowess. Interestingly,
@Robinson2000 reviewed another extreme contrasting giftedness in mental power
spectral plane, where they examined how mental retardation posed similar risk
on burdened by social pressure and expectation. Said argument further supports
the need of designing appropriate educational system, culture and environment
to fully optimize individual talents [@Reis]. A quantitative study on Germany
enrichment programme concluded better cognitive measurement in programme
participants compared to the controlled group [@Welter2018]. While
@Smedsrud2018 reported better education quality in acceleration programme, even
though it did not meet certain supportive aspects for mathematically-gifted
students.

# Final Excerpt

While several studies delineated biological properties on intelligence and
giftedness, the causality among underlying factors still require further
investigations. Enrichment and acceleration programme may help furthering
cognitive aptitude in well-defined problem space, but ill-defined problem space
remains unresolved.

# References
