---
author: lam
slug: hydronephrosis-prognosis
date: 2019-03-02
categories: ["urology"]
tags: ["prognosis", "hydronephrosis"]
reading_time: true
title: |
  Predicting Hydronephrosis Prognosis in Obstructive and Nonobstructive Cases
description: >
  Hydronephrosis is a dilatation of pyelum and/or calyces. In a pathological
  event, such condition can happen following an obstructive or nonobstructive
  causes. Differences in underlying ethiologies affects the prognosis of
  hydronephrosis. Hence the question, what prediction can we make on the
  prognosis of hydronephrosis given the information related to its underlying
  problem?  In this literature review, database from PubMed and ScienceDirect
  are used to find relevant articles.  Concurrence with malignancy, creatinine
  clearance rate, glomerular filtration rate, carbohydrate antigen 19-9, kidney
  injury molecule-1 and thickeness of renal cortices are suggested as potential
  predictors. On the other hand, not enough evidence to show the possibility of
  using haemoglobin to predict the outcome of hydronephrosis treatment.
summary: >
  Hydronephrosis is a dilatation of pyelum and/or calyces. In a pathological
  event, such condition can happen following an obstructive or nonobstructive
  causes. Differences in underlying ethiologies affects the prognosis of
  hydronephrosis. Hence the question, what prediction can we make on the
  prognosis of hydronephrosis given the information related to its underlying
  problem?  In this literature review, database from PubMed and ScienceDirect
  are used to find relevant articles.  Concurrence with malignancy, creatinine
  clearance rate, glomerular filtration rate, carbohydrate antigen 19-9, kidney
  injury molecule-1 and thickeness of renal cortices are suggested as potential
  predictors. On the other hand, not enough evidence to show the possibility of
  using haemoglobin to predict the outcome of hydronephrosis treatment.
bibliography: ref.bib
csl: ../vancouver.csl
draft: false
---

# Introduction

Hydronephrosis is a terminology to describe dilated pelvis with or without the
involvement of its calyces, which happen due to physiological or pathological
condition.[@Mevorach2007] In a physiological condition, the dilatation of
urinary tract structure can occur following certain events such as diuresis,
increased intra-abdominal pressure (e.g: straining) also by the influence of
gravity.[@Murnaghan1958] Such dilatation is important to allow efficient urine
expulsion from the renal pelvis.[@Murnaghan1958; @Roshani2003]

However, in a pathological condition, dilatation of the urinary tract structure
is instead aggravated by either obstructive, nonobstructive or neurogenic
cause.[@Vaidyanathan2012; @Choi2015; @Zambon2018; @Tran2014] In women,
hydronephrosis can be found during pregnancy and pelvic organ
prolapse.[@Hui2011; @Dancz2015; @Nuraj2017] Meanwhile, in men, hydronephrosis
may follows Benign Prostatic Obstruction and Urothelial Carcinoma.[@Riyach2014;
@Byers2018] Regardless of gender, another common cause of hydronephrosis
including renal stone, ureter stone and neurogenic bladder.[@Vaidyanathan2012;
@Choi2015]. To a lesser degree, hydronephrosis can also be induced by
infection, drug administration as well as radiotherapy.[@Lojanapiwat2002;
@Kurata2016; @Orchard2016] Therefore, complaints related to hydronephrosis may
vary, depending on the underlying cause.

Diagnosis of hydronephrosis can be done through careful clinical investigation
and USG screening.[@Nuraj2017] Grading of hydronephrosis can be made
subservient to the grading system proposed by Society for Fetal Urology
(SFU).[@Fernbach1993] This grading system delineates five distinctive grade,
with grade 0 being normal condition and grade 4 is the severe finding.

Without addressing the etiological cause of hydronephrosis, managing such
cases would prove unwieldy. The recurrence of hydronephrosis is highly related
to the source of obstruction or peristaltic disturbances.[@Jespersen2005;
@Zhu2012; @Chiancone2017] Furthermore, if the case of hydronephrosis is not
well treated, it may cause irreversible structural changes. These changes may
possibly deteriorate renal function.[@Marchini2016; @Balikci2015] The presence
of hydronephrosis is also crucial in determining the prognosis and disease
progression.[@Patel2014; @Pradhan2011; @Luo2013]

Therefore, can we delineate each factor that may contribute to determining the
prognosis of hydronephrosis cases? In this literature review, such query shall
be challenged by current advancement in hydronephrosis understanding.

# Method

Thorough literature search is done using PubMed and ScienceDirect. Keywords
being used in PubMed including "Hydronephrosis [MeSH]", "Prognosis [MesH]",
"Urogenital System [MeSH]", "Obstruction", "Congestion", "Blockage" and
"Restriction". In the query, "Pyonephritis [MeSH]" is excluded from the result,
then "Homo sapiens" as well as "Adult [MeSH]" are being set as filters. In
ScienceDirect, keywords being used are "Hydronephrosis", "Treatment" and
"Prognosis". Filter being applied in this query only includes review article as
desired output.

Selecting articles published during the last five years, 43 results
were obtained, which then manually screened by reading the abstract and the
full paper. Afterwards, 11 articles were selected as main references. From such
articles, relevant citations were also thoroughly examined to include any
important findings and case reports.

# Discussion

## Renal Physiology

In this part, we may want to shift our focus on two main physiological changes
which occur during hydronephrosis. This part explains the nature of glomerulus
filtration process as well as peristaltic movement in urinary tract.

### Glomerulus Filtration

Represented by the Glomerular Filtration Rate (GFR), the flow of plasma through
glomerulus over certain period of time defines renal function. Maintaining the
GFR requires careful regulation of the Renal Perfusion Pressure
(RPP),[@Koeppen2013] where as we shall see in later section decrease of such
pressure will negatively affect the GFR.[@Carlstrom2015]

### Peristaltic Movement

Urinary tract peristalsis occur due to the activity of myogenic contraction as
well as prostaglandin and neurpeptide release to maintain such
contractility.[@Nguyen2016; @Davidson2000] Myogenic contraction is first
initiated by propagation of action potential through the activation of atypical
smooth muscle cell as a pacemaker, located proximal to pelviocalyceal region.
Electrical signal produced by the aforementioned cell elicit the activity of
adjacent muscular region of renal pelvis. Such electrical activity is then
propagated to the ureter, enabling peristalsis of urinary tract.[@Davidson2000]
To maintain the peristaltic movement, recent finding suggests the importance of
prostaglandin and neuropeptide secretion.[@Nguyen2016] Release of such
substances firstly started by stimulation of primary sensory nerves which then
release inotropic and chronotropic agents. These agents induce the secretion of
tachykinines and Calcitonin Gene-Related Peptide (CGRP), which act in opposite
manner. Tachykinine acts as an excitatory component to induce the release of
inotropic and chronotropic agents, while CGRP plays a role as inhibitoric of
such agents to be secreted.[@Nguyen2016] Production of prostaglandin and
neuropeptide helps to regulate intracellular Ca^2+^ concentration, thus
maintaining peristalsis.[@Nguyen2016]

## Pathophysiology in Hydronephrosis

Being elucidated in this paper are two possible pathways to develop
hydronephrosis in adult. Being the most prevalent one, obstructive
hydronephrosis shall be on the spotlight, where the pathogenesis, nephron
feedback response and anatomical source of obstruction are elaborated.
In nonobstructive hydronephrosis part, the contribution of vesicoureteral
reflux as well as upper and lower motor neuron are further described.

### Obstructive Hydronephrosis

Relative to the rate of urine production, inadequate urine drainage due to
urinary tract blockage can cause hydronephrosis. During acute settings within
6-48 hours, increased pressure is followed by increasing intraparenchymal
vascular resistance, which will subside after 48 hours. However, prolonged
state of hydronephrosis may lead into diminution of arteriovena circulation,
hence provoking renal injury, fibrous tissue formation and tubular
atrophy.[@Byers2018; @Murnaghan1958]

The increase of pressure may also further decrease GFR by the modulation of
myogenic vasoconstriction response and Macula Densa-Tubuloglomerular Feedback
(MD-TGF) response. Increased pressure causes vascular smooth muscle stretching,
which will activate mechanotransduction pathway. Activation of such pathway
elicit membrane depolarization, thus inducing Ca^2+^ ion release in cytosol.
The presence of Ca^2+^ mediates the detachment of tropomyosin from myosin,
hence enabling myosin to bind actin.[@AitchisonSmith2018] Adhesion of myosin
into actin further cause muscular contraction, and therefore vasoconstriction
of the afferent arteriol. On the other hand, increased Renal Perfusion Pressure
also affect signal transduction to Macula Densa. This transduction is also
directly cause an adjustment of afferent arteriol
vasoconstriction.[@Carlstrom2015]

Source of obstructive problem can arise in either the ureter, bladder or
urethra. Within ureter, stone formation is the most probable cause of
obstruction,[@Byers2018] followed by malignant and benign mass compression.
Cause of bladder obstruction could be due to urothelial carcinoma, which should
be considered in older patients with haematuria.[@Zambon2018; @Byers2018]
Obstruction of the urethra including those of functional, benign and malignant
origin, with Benign Prostatic Hyperplasia being the most prevalent case in
older male.[@Byers2018]

### Nonobstructive Hydronephrosis

The case of hydronephrosis due to nonobstructive origin is related with nervous
function and peristaltic movement. In such cases, the event of vesicoureteral
reflux may explain the dilated pelvis and calyces. In a study by Aboutaleb, et
al., vesicoureteral reflux degree is found to be correlated with the degree of
hydronephrosis.[@Aboutaleb2003]

Hydronephrosis is also a possible occurrence in an upper motor neuron diseases.
Twenty percent of adult with cerebral palsy in a study by Cotter, et al. is
also diagnosed as having hydronephrosis.[@Cotter2016] Similarly, this case can
also be found in a spinal cord injury with inadequate neurogenic bladder
management.[@Downs2014] Problem in upper motor neuron may lead to detrussor
sphincter dyssinergia (DSD), causing a bladder outlet obstruction due to
abnormal detrussor muscle contractility and involuntary sphincter
activation.[@Stoffel2016] Therefore, the presence of upper motor neuron-related
neurogenic bladder can precipitate hydronephrosis.[@Gormley2010]

## Management of Urinary Retention

The key point of hydronephrosis management is to release the tension due to
increased pressure following urinary retention.[@Stoffel2017] Several
approaches can be done to attain the objective, for instances by catheterising
the patient, placing ureteral stent, performing percutaneous nephrostomy, or even
carrying out pyeloplasty if indicated.[@Stoffel2017; @Nayyar2016; @Dagli2011;
@Patel2017; @Flukes2015]

Applying different management approach by categorizing the patient into
high-risk and non high-risk group posit better clinical outcomes.
Categorization is done based on signs and symptoms as well as laboratory and
radiographic findings. In this review, only high-risk group is of interest
since this group encompasses subjects with hydronephrosis. Asides from
diagnosed as having hydronephrosis, high risk patients also include those who
complain overflow urinary incontinence, are diagnosed with Chronic Kidney
Disease (CKD) and have estimated Glomerular Filtration Rate (eGFR) around
30-44%, experience urosepsis during the last six months and have recurrent
symptomatic Urinary Tract Infection (UTI) more than three times within the past
12 months.[@Stoffel2017]

In managing high-risk group, we may want to start from less invasive treatment
to release the built-up pressure due to urinary retention. Initial treatment
can be done by inserting a urinary or suprapubic catheter to reduce retained
urine. Risk reduction can also be done by starting specific medication, i.e
treat UTI with antibiotics. In this step, should the patient does not get any
improvement, we may also need to consider surgical intervention.[@Stoffel2017]

Afterwards, reassessment can be done by performing physical examination and
renal USG to confirm hydronephrosis, urine microscopy or culture to assert
infection and eGFR to affirm CKD. Urodynamic should also be considered if we
want to assess treatment efficacy on the underlying cause of hydronephrosis,
for instances Bladder Outlet Obstruction, Bladder Compliance and Vesicoureteral
Reflux.[@Stoffel2017]

## Prognosis of Hydronephrosis

The clinical outcome of hydronephrosis is highly influenced by its underlying
condition, where patients with certain diagnosis may have different prognosis
compared to the other.[@Kurata2016; @deSousaMorais2018] Being described in this
paper are three perspective on viewing the prognosis, namely *ad vitam*, *ad
functionam* and *ad sanationam*. *Ad vitam* explains the impact of
hydronephrosis on overall chance of survival. Meanwhile, *ad functionam*
defines the functional outcome of nephrons following physical insult due to
increased pressure in the presence of hydronephrosis. Lastly, *ad sanationam*
describes the recurrence rate of hydronephrosis based on its underlying
problem.

### *Ad Vitam*

Cervical malignancy preceding the case of hydronephrosis is a predictive factor
for higher morbidity and mortality, even with adequate treatment.[@Patel2014;
@Pradhan2011] In this condition, the presence of hydronephrosis is usually
accompanied by reduced renal function, which may impede the drug excretion.
Moreover, drug dose adjustment may be required, thus increasing the risk of
being suboptimally treated.[@Patel2014]

### *Ad Functionam*

In the case of obstructive hydronephrosis, prompt treatment of its underlying
cause may yield beneficial outcome for the patient. Should the underlying cause
get resolved while maintaining GFR > 10mL/min/1.73m^2^, patients will more
likely to have favourable prognosis. Within such condition, renal injury can be
completely or partially resolved.[@Byers2018] 

Albeit the result obtained by Hoshino, et al. might be confounded by age of
participants, lower creatinine clearance rate can be found in subjects with
higher grade hydronephrosis. In this study, lower grade hydronephrosis can
present creatinine clearance rate $\geq$ 50mL/min. [@Hoshino2012] Denoting a
deteriorative facet of hydronephrosis, this result is also strongly supported
by another study, where silent ureter stone may lead to hydronephrosis and
irreversible renal function decline.[@Marchini2016] Decline of function is
mostly related to the decaying persitaltic activity, whereas in Hydronephrotic
patients is found to be significantly lower compared to control group. Lower
peristaltic movement happened due to reduced number of Cajal-like cells along
lamina propria and muscularis propria.[@Balikci2015]

Hydronephrosis grading is also a good predictor for stone detection, where
urinary stone is found to be more prevalent in higher grade
hydronephrosis.[@Alshoabi2018] This finding support a study by Amini, et al.
where the concentration of Carbohydrate Antigen (CA) 19-9 is proposed as a
potential biomarker for detecting renal damage associated with obstructive
uropathy in patients with urinary stones and hydronephrosis. In his study, CA
19-9 concentration is elevated during insulting period due to increased
pressure caused by urinary retention.[@Amini2016]

During the event of hydronephrosis, function of affected kidney could be
compromised,[@Byers2018] leading to temporary functional cessation. Should it
be further aggravated, such condition may persist as an Acute Kidney Injury
(AKI).[@Rahman2012; @Sandberg2017; @Gosmanova2009] As a response of systemic
stress in a critical condition on AKI, erythropoietin is released stimulated by
IGFBP-1. However, no evidence supporting the presence of erythropoietin and
increasing haemoglobin in patients with AKI.[@Yamashita2016] Hence, alteration
of haemoglobin concentration might not be a reliable marker in predicting
clinical outcome of hydronephrosis.

Kidney Injury Molecule-1 (KIM-1) is also proposed as a potential biomarker for
hydronephrosis and obstructive nephropahty-induced AKI.[@OlveraPosada2017;
@Shao2014; @Jin2017]. Urinary concentration of KIM-1 is found to be
significantly higher in urinary stone patients with hydronephrosis as compared
to urinary stone patients without hydronephrosis.[@OlveraPosada2017] In a
recent meta-analysis, utilization of KIM-1 to detect AKI demonstrated an area
under the curve of 0.86.[@Shao2014] In an animal model, urine concentration of
KIM-1 followed a time-dependent increase, reflecting AKI progression in
unilateral urinary obstruction group.[@Jin2017]

Cortical thinning is another signs that can be radiographically observed in
patients with hydronephrosis.[@Hansen2015] Reduction of cortical thickness may
reflect atrophy in hydronephrosis pathogenesis.[@Byers2018] Thinner cortical
structure also impacts the overall function of the kidney, marked by decreasing
GFR (r=0.478; p<0.001).[@Yamashita2015] In the aforementioned study, the range
of upper third cortical thickness is 0.38 -- 1.36cm and the range of middle third
cortical thickness is 0.37 -- 1.18cm. From the same study, no statistical
correlation has been found between parenchymal thickness and the GFR.[@Yamashita2015]

### *Ad Sanationam*

Hydronephrotic patients with gastrointestinal cancer is less compliant to
ureteral stent treatment and more prone to experience stent
failure. In such cases, performing percutaneous nephrostomy would yield a
better result.[@Ohtaka2018] Hydronephrosis grading has also been found associated
with non-organ-confined ureteric cancer as well as bladder cancer
recurrence.[@Luo2013]

# Conclusion

Hydronephrosis is a clinical finding hallmarked by the presence of dilated
pelvis and its calyces. It can arise due to myriad factors which can be
categorized into obstructive and nonobstructive origin. Holistic treatment of
hydronephrosis requires physician to address the underlying cause.
Symptomatically, such treatment can be achieved by reducing the urinary
retention, thus minimizing the dilation. Prognosis of such treatment can be
predicted by several factors. The absence of malignancy underlying
hydronephrosis, prompt treatment while maintaining GFR > 10mL/min/1.73m^2^,
creatinine clearance rate $\geq$ 50mL/min, low CA 19-9, low urinary KIM-1
concentration and thick cortical structure are predictors of good clinical
outcome. However, not enough evidence has been found to eliminate or confirm
haemoglobin as another potential biomarker.

# Reference

\fontsize{9}{11}\selectfont
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{4pt}
\indent
