---
author: lam
title: Network Simulation on COVID-19
slug: network-simulation-covid
tags: ["medicine", "simulation"]
categories: ["analysis"]
draft: true
---

```{r init, eval=TRUE, echo=FALSE}
load("analysis.RData")
```

# Preamble

The increasing numbers of publicly available data on COVID-19 infection enabled
a few computational approaches to emerge. Previously presented in YouTube,
where Grant Sanderson proposed
[https://www.youtube.com/watch?v=Kas0tIxDvrg&t=28s](COVID-19 epidemic as
meriting an exponential growth). Another explanation in The Washington Post
also greatly appealed computational modelling on
[https://www.washingtonpost.com/graphics/2020/world/corona-simulator/](how to
flatten the curve of coronavirus outbreak). Both regard social dynamic as a
random event, where population spatial movement depicted as either permutation
changes or Brownian motion. In this simulation, I wish to use network modelling
as a layer of abstraction in explaining population movement and COVID-19 growth
rate. Furthermore, by applying edges deletion from such a network, we may
visualize how social distancing and self-quarantine may help reducing the viral
transmission. In creating such a network, Watts-Strogatz small world model will
represent general population and Markov Chain will estimate the probability of
having infection.

# Initial Assessment

A table acquired from
[https://github.com/CSSEGISandData/COVID-19/blob/master/who_covid_19_situation_reports/who_covid_19_sit_rep_time_series/who_covid_19_sit_rep_time_series.csv](Johns-Hopkins
GitHub repository) concatenated widely-available WHO time series data dated
from 21 January to 5 March 2020. On the first visual inspection, data seems to
have missing value due to temporal differences in first outbreak onset. Only
data from China and global countries besides China (referred as "Outside" from
this point onward) being considered on initial data exploration.

- Compare data in China and outside China
- Check the infection rate

# Simulation Preparation

# Applicability

# Conclusion
