---
author: lam
title: Why do we perceive emotion?
description: >
  In this enquiry, I would like to describe the interpretive facet of emotion
  according to its probable origin. This post could neither, by any means,
  considered as an intellectually challenging nor evidently approved argument.
  This post only serves a purpose as a reflection on my humble perspective
  concerning this topic. Nonetheless, any kind of intelligible counter-argument
  or positive criticism will still be highly appreciated.
summary: >
  In this enquiry, I would like to describe the interpretive facet of emotion
  according to its probable origin. This post could neither, by any means,
  considered as an intellectually challenging nor evidently approved argument.
  This post only serves a purpose as a reflection on my humble perspective
  concerning this topic. Nonetheless, any kind of intelligible counter-argument
  or positive criticism will still be highly appreciated.
slug: emotion-perception
date: 2019-11-14
categories: ["thought"]
tags: ["opinion", "cognition", "emotion"]
---

In this enquiry, I would like to describe the interpretive facet of emotion
according to its probable origin. This post could neither, by any means,
considered as an intellectually challenging nor evidently approved argument.
This post only serves a purpose as a reflection on my humble perspective
concerning this topic. Nonetheless, any kind of intelligible counter-argument
or positive criticism will still be highly appreciated.

Emotion is supposedly divided into imperceptible and perceptible ones.
Imperceptible emotion holds the definition of physiological responses toward
any sensible stimuli, regardless of its perceivable nature. Imperceptible
emotion manifests as bodily adjustments, e.g changes in lacrimal gland's
production, the rate of heart pump, skeletal muscles contractility, etc.
Aforementioned changes are regarded as imperceptible due to the lack of
conscious thinking in perceiving its process.

On the other hand, perceptible emotion defines experience as a process of
projecting and reforming a stimulus into a conscious perception. This emotion
is further categorised into a spectrum of sadness, anger, happiness, etc.
Comprehending the mechanism of perception is deemed necessary, but does not
have to be resolved prior to this enquiry. For the abstraction of human
perception is yet to be discovered, dwelling into this matter will only stray
me further from the primary intention of this post. Henceforth, I would like to
suggest the origin of emotion as either one of these models:

1. A psychosocial developmental advancement
2. A lack of language expression

Advancement in psychosocial development may happen in accordance with the
Hebbian theory of learning. According to Donald Hebb, learning may occur
jointly with increasing neuronal connection efficacy. In obtaining such
efficacy, the neuron has to increase its connecting property towards several
neurons while diminishing its connection with several others. This process may
result in habituation, marked by reduced perceptibility of certain process.
From this point of view, We may observe emotion as the result of a certain
stimulus without taking its intermediary process into account.

The second model in this discourse is emotions as consequences from lack of
language expression. To a lesser degree, we have observed how much language
plays a role in expressing abstruse ideas. In order to explain my notion, let
me take the Dani people of New Guinea as an example. In Dani language, colours
are distinguishable as mili (dark colour) and mola (warm colour). Lack of word
preferences impedes them from categorizing yellow as a different colour
compared to red. In the polar extreme, I would like to take Russian blue
(goluboy and siniy) as an example. Two colours in the blue spectrum are easily
distinguishable by people of Russian origin, but those who are not familiar
with these colours may fail to notice the differences at a glance. In short,
language shapes our perception and lets us express ideas in different ways. The
case of colour perception in Dani people and Russian may help in explaining how
language impacts the idea formation. We may speculate further that emotion may
be regarded as it is today due to the lack of language expression to explain
its intermediary process.
