---
author: lam
title: Linux command line
slug: terminal-setup
date: 2020-01-18
projects: []
categories: ["technology"]
tags: ["linux", "command line", "workflow"]
draft: true
summary: Why does it matter?
---

Using Linux for several years help me develop a different perspective on using
the computer. We, as user, can have indefinite control over our system. Of
course, we can accomplish the same (or at least nearly equivalent) goal using
other systems, but I'd love to limit the scope of this article to Linux.
Besides my familiarity with Linux, I couldn't find other reasons to not
elaborate command line workflows on other system.

# Why command line?

> Command line is very simple, it only takes genius to understand its
> simplicity

Working on the [command line]() could be a very daunting challenge at
first, especially for those familiar with graphical user interface (GUI). Using
GUI, it's extremely simple to perform a task, where the least arduous task only
require the user to point and click specific button, and *voila*, it's done!
However, imagine you need to click the same button [for]() hundreds of
thousand in a day to repeat the same task continuously, wouldn't that be a
nightmare?  Here comes the first perk of using command line, where your
computer will handle the seemingly [repetitive task]() tirelessly.

Remember the last time you need to follow countless steps to perform certain
task, only to repeat it from zero due to some silly mistake? [Command line]()
shall introduce you one of its convenient feature: [history buffer](). Well,
okay, not all Linux shell has history buffer. But to be fair, most of Linux
distros use `bash` as their shell, which of course merit the comfort of having
a history buffer. With history buffer, you can access issued commands, making
the process repeatable and reproducible.

In [command line](), you can do one thing, and do it well. But how if you need
to do multiple things consecutively? Fret not, for the [shell script ]() is
there for you! Generally speaking, you can put your commands into a text file,
where each command separated by semicolon (`;`) or a newline. And there you go,
you will have your first shell script. Yes, it is oversimplifying things, but
it's better to start simple and build up your script bit by bit.

# But, where do I start?

It depends! Things you want to do and tools you want to use will affect how you
should start on using the command line. In command line, you can do something
as simple as connecting to WiFi, and you can also manage torrent files in
background while limiting the speed when your connection is unstable and you
need to prioritize other task requiring internet. The possibility could be
endless, only you and your imagination (and documentation of course) can limit
your voyage in command line endeavour. I would rather suggest making an outline
of what you'd like to accomplish using command line, and start writing your
first script. It may look messy, but it will be something you can call your
own. Not to mention the satisfying feelings you get when finishing your first
script knowing it works like a charm!
