---
author: lam
title: Review on psychopathy
slug: rev-psychopathy
date: 2017-08-03
draft: true
categories: ["psychology"]
tags: ["personality", "behaviour"]
bibliography: ref.bib
csl: ../vancouver.csl
---

# Biased Response in Self-report Psychopathy Scale[@Ray2013]

## Tendency

* Faking Good	: Pretend to be a good person
* Faking Bad	: May malinger psychiatric symptoms

### Affective-Interpersonal Factors:

* Superficial charm
* Narcissism
* Deceptive
* Shallow affective experiences
* Guiltlessness

### Antisocial Deviance Factors:

* Impulsive
* Irresponsible
* Boredom
* Intentional dependence
* Aggressive

## Validating Instruments:

* Balanced Inventory of Deceptive Responding
* Structured Interview of Reported Symptoms
* Marlowe-Crowne Social Desirability Scale

## Results

* Self-reported psychopathy subjects are more likely to *faking-bad*
* PPI/R F1 tested subjects produce non-conforming validation result

# Pyschopathy and Moral Judgment[@Marshall2018]

## Moral Judgment measurement tools:

* Sacrificial moral dilemmas 	-> personal and impersonal dilemmas: different
  course of action?
* Kohlbergian moral reasoning 	-> preconventional, conventional,
  postconventional
* Moral Foundation questions 	-> moral concern: perception and
  decision-making of others

### Kohlberg's Moral Stages:

* Preconventional	: Avoid punishment, preserve self-interests
* Conventional		: Act in accordance with authorities' intentions
* Postconventional	: Able to develop their own set of moral

### Moral Foundation Theory

* **C**are	: Disapproval of conditions which inflict other's sufferings
* **A**uthority	: Respect for tradition
* **L**oyalty	: Self-sacrifice for the group
* **F**airness	: Equity / proportionality
* **S**anctity	: Disgusts elicited by certain act regardless its concequence

## Results

* Significant correlation between psychopathy and moral deficits
* Small relationships albeit it's statistically significant

## Key Points:

1. Psychopath **DO** understand moral, but insufficiently motivated to follow
   it
2. Psychopathy **does NOT** correlate with moral stages development (still
   a controversy?)
3. Psychopath may **diminishes** certain domains of moral concern

# VBM: Brain Structure and Interpersonal Violence[@Lamsma2017]

Hypothetically Inflicted Areas:

* Orbitofrontal Cortex
* Dorsolateral Prefrontal Cortex
* Amygdala
* Hypocampus
* Anterior Cingulate Cortex

## Modalities:

* Computed Tomography
* Magnetic Resonance Imaging
* Diffusion Tensor Imaging (diffusion MRI)

## Results:

* Reduced parietal lobe grey matter volume in subjects who tend to commit
  interpersonal violence
* No significance change in aforementioned areas

## Limitations:

* Studies only included structural differences
* There may be a neural connectivity differences

# References
